### ISSUE TITLE
Tests still being counted in coverage

### ISSUE THREAD

**Issue by Druthyn** [taiki-e/coverage-helper#5]
Hi
I'm running cargo-llvm-cov on a no_std library, and was intending to use coverage-helper to ignore the unit tests from being tracked for coverage.

Following the README, I've got
`[dev-dependencies]
coverage-helper = "0.2.2"`
in cargo.toml,
`#![cfg_attr(all(coverage_nightly, test), feature(coverage_attribute))]` 
in lib.rs, and 
`use coverage_helper::test;` 
at the top of each `tests` module in each file.

Despite this, all test functions in the `tests` modules are being tracked by llvm-cov. using rust analyzer in vs-code, the macro expansion of `#[test]` is simply generating `Not available`, but I'm unable to figure out why. Do you have any insights into why my setup isn't working? 

Thanks in advance for your support.

**Comment by taiki-e** [comment]
Please provide information on the code that encountered the problem and the version of the compiler that encountered the problem.
In particular, please provide reproducible examples if possible.

**Comment by Druthyn** [comment]
Thank you for your response.
On getting the rustc version (it was 1.79.0) I realised it could be updated. Doing so now produces this warning when running `cargo test` or lcov:

![image](https://github.com/user-attachments/assets/862d705d-c283-418f-9e6e-fd42cb20c33f)

This occurs in my main project, and in [this minimal example](https://github.com/user-attachments/files/16482309/cov_help_test.zip)
(cargo init --lib, follow README instructions).

`$ rustc -V`
`rustc 1.80.0 (051478957 2024-07-21)`

**Comment by taiki-e** [comment]
> rustc 1.80.0 (051478957 2024-07-21)

This is stable channel, but since `#[coverage(off)]` is unstable so coverage-helper (and `#![cfg_attr(all(coverage_nightly, test), feature(coverage_attribute))]`) only enable `#[coverage(off)]` (exclude from coverage) on nightly channel.

[cargo-llvm-cov doc](https://github.com/taiki-e/cargo-llvm-cov#exclude-function-from-coverage) says:

> Since #[coverage(off)] is unstable, it is recommended to use it together with cfg(coverage) or cfg(coverage_nightly) set by cargo-llvm-cov.

> cfg(coverage_nightly) is set when using cargo-llvm-cov with nightly toolchain (unless --no-cfg-coverage-nightly flag passed)

And [our doc](https://github.com/taiki-e/coverage-helper#examples) says:

> Expanded to:
> 
> ```rs
> #[cfg_attr(all(coverage_nightly, test), coverage(off))]
> ```

---

> Doing so now produces this warning when running cargo test or lcov:

This is explained in [cargo-llvm-cov doc (the same section as above)](https://github.com/taiki-e/cargo-llvm-cov#exclude-function-from-coverage):

> Rust 1.80+ warns the above cfgs as `unexpected_cfgs`. The recommended way to address this is to add a [`lints` table](https://doc.rust-lang.org/nightly/rustc/check-cfg/cargo-specifics.html#check-cfg-in-lintsrust-table) to `Cargo.toml`.
> 
> ```toml
> [lints.rust]
> unexpected_cfgs = { level = "warn", check-cfg = ['cfg(coverage,coverage_nightly)'] }
> ```

**Comment by GyulyVGC** [comment]
Hi @taiki-e I've followed all the suggestions in this thread, but still I wasn't able to exclude unit tests from covered lines.

1. I'm setting `#![cfg_attr(all(coverage_nightly, test), feature(coverage_attribute))]` at the top of my `lib.rs`
2. My `Cargo.toml` contains:
    - `[lints.rust] unexpected_cfgs = { level = "warn", check-cfg = ['cfg(coverage,coverage_nightly)'] }`
    - `coverage-helper = "0.2.2"` in the dev-dependencies
3. I'm running tests with `RUSTUP_TOOLCHAIN=nightly cargo llvm-cov --open --ignore-filename-regex proto/*`

What am I missing?

**Comment by taiki-e** [comment]
@GyulyVGC Please provide information I said in https://github.com/taiki-e/coverage-helper/issues/5#issuecomment-2266821120.

> RUSTUP_TOOLCHAIN=nightly cargo

Using `cargo +nightly` instead of this will still cause problems?

> --ignore-filename-regex proto/*

`proto/*` is looks glob not regex, in regex I think you have to use `proto/.*`.

**Comment by GyulyVGC** [comment]
@taiki-e thanks for your prompt response.

> @GyulyVGC Please provide information I said in [#5 (comment)](https://github.com/taiki-e/coverage-helper/issues/5#issuecomment-2266821120).

Generated by llvm-cov -- llvm version 19.1.1-rust-1.84.0-nightly

> Using `cargo +nightly` instead of this will still cause problems?

Unluckily yes 😞 

> `proto/*` is looks glob not regex, in regex I think you have to use `proto/.*`.

This is not part of the problem, files in my `proto` directory are correctly excluded, the only problem are unit tests.

**Comment by taiki-e** [comment]
> > @GyulyVGC Please provide information I said in [#5 (comment)](https://github.com/taiki-e/coverage-helper/issues/5#issuecomment-2266821120).
> 
> Generated by llvm-cov -- llvm version 19.1.1-rust-1.84.0-nightly

In https://github.com/taiki-e/coverage-helper/issues/5#issuecomment-2266821120, I said:

> Please provide information on the code that encountered the problem and the version of the compiler that encountered the problem.
> In particular, please provide reproducible examples if possible.

Could you provide information on the code that encountered the problem too not only compiler version?

It is always difficult to investigate an issue unless I can reproduce it on my end.

**Comment by GyulyVGC** [comment]
Unfortunately the repository is private and I cannot provide more info about the code itself.
Anyway, it's just a normal library with some unit test.

**Comment by GyulyVGC** [comment]
Ok, I've found out the problem.

I had to include `use coverage_helper::test;` in the test modules. Is this documented?

One more problem still remains though: this excludes functions marked with `#[test]`, but not helper functions in the test module that despite not being real tests, are used by tests.

I don't know if it's possible, but a way better solution would be to introduce to cargo-llvm-cov a new attribute to exclude Rust modules named in a certain way. So that users can exclude for example modules named "tests", where unit tests are conventionally included.

**Comment by taiki-e** [comment]
> Is this documented?

https://github.com/taiki-e/coverage-helper?tab=readme-ov-file#examples

> One more problem still remains though: this excludes functions marked with `#[test]`, but not helper functions in the test module that despite not being real tests, are used by tests.

In the recent rustc, it seems the module-level `coverage(off)` is supported:

```rs
#[cfg(test)]
#[cfg_attr(coverage_nightly, coverage(off))] // <---
mod tests {
   // ...
}
```

(Perhaps this library should be deprecated for most cases in favor of the module-level `coverage(off)` ...)

**Comment by GyulyVGC** [comment]
Thanks so much for this suggestion!

I just tried it and it's exactly what I was searching for 🙏
